### PR TITLE
[licence-checker] Add vlt template file support

### PR DESCRIPTION
**Pull request by hcindyl**
Signed-off-by: Cindy Liu <hcindyl@google.com>

### CODE REVIEW

**Comment by hcindyl** [comment]
Need to make this change for https://github.com/lowRISC/opentitan/pull/11810

**Review by rswarbrick — APPROVED** [review]

**Comment by rswarbrick** [comment]
Thanks, @hcindyl!

**Comment by rswarbrick** [comment]
The failing lint check isn't caused by your change (and I'm not sure what's going on there - maybe a tool change?) Anyway, merging now!

**Comment by hcindyl** [comment]
oh no, I sent out the wrong string... :( Will have another fix PR. Sorry about that.

**Comment by hcindyl** [comment]
Fixing PR at https://github.com/lowRISC/misc-linters/pull/24

**Pull request merged**
